DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NICKNAME    VARCHAR(30) NOT NULL,
    GENDER     VARCHAR(10) NOT NULL,
    EMAIL       VARCHAR(50) NOT NULL
)
