DROP TABLE IF EXISTS PET;

CREATE TABLE PET
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME           VARCHAR(30) NOT NULL,
    TYPE           VARCHAR(30) NOT NULL COMMENT '반려동물 종류',
    KIND           VARCHAR(30) NOT NULL COMMENT '품종',
    BIRTH          DATE        NOT NULL COMMENT '출생년도',
    GENDER         VARCHAR(10) NOT NULL COMMENT '성별',
    NEUTRALIZATION TINYINT     NOT NULL COMMENT '중성화 여부',
    PROFILE_IMAGE  VARCHAR(100) COMMENT '프로필 이미지'
)