name: PR Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: 테스트 자동화
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      actions: read

    steps:
      - name: Repository 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.ref }}

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            *.gradle*
            **/gradle-wrapper.properties

      - name: Gradle 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트 실행
        run: ./gradlew test

      - name: 테스트 결과 PR에 코멘트 등록
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'build/test-results/test/TEST-*.xml'

      - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: 테스트 실패 시, 슬랙으로 알람 발송
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: author, pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
